name: (manual) check updated plugins
env:
  github_token: ${{ secrets.GITHUB_TOKEN }}
on: 
  workflow_dispatch:
jobs:
  First:
    name: check updated
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
#      - name: Install beautifulsoup4 and Pillow
#        run: |
#          python3 -m pip install bs4
#          python3 -m pip install lxml
#          python3 -m pip install Pillow
      - name: Check nowfor updates
        run: python res/checkupdates.py
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add 'data/'
          git commit -m "data updated" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Upload versions to release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Downloads
          tag: Latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "temp/*.zip"
